replicaCount: 3

image:
  repository: ${IMAGE_REPO}
  pullPolicy: IfNotPresent
  tag: ${DOCKER_TAG}

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enable: false
  hostname: ${HOST_NAME}
  secretName: ${SECRET_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.org/redirect-to-https: "true"

podAnnotations: { }

resources:
  limits:
    cpu: '1'
    memory: 500Mi
  requests:
    cpu: '1'
    memory: 500Mi

configMapMetrics:
  METRICS_ENABLED: "${METRICS_ENABLED}"
  METRICS_ENDPOINT: "${METRICS_ENDPOINT}"
  METRICS_PORT: "${METRICS_PORT}"
