replicaCount: 3

image:
  repository: ${IMAGE_REPO}
  pullPolicy: IfNotPresent
  tag: ${DOCKER_TAG}

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  hostname: ${HOST_NAME}
  secretName: ${SECRET_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.org/redirect-to-https: "true"

podAnnotations: {}

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 128Mi

configMap:
  SERVER_PORT: "${SERVER_PORT}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_USERNAME: "${REDIS_USERNAME}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_DB: "${REDIS_DB}"
  MYSQL_HOST: "${MYSQL_HOST}"
  MYSQL_PORT: "${MYSQL_PORT}"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  MYSQL_DB: "${MYSQL_DB}"
  JWT_SECRET: "${JWT_SECRET}"
  JWT_ALGORITHMS: "${JWT_ALGORITHMS}"
  LOG_PATHNAME: "${LOG_PATHNAME}"
  LOG_FILENAME: "${LOG_FILENAME}"
  METRICS_ENABLED: "${METRICS_ENABLED}"
  METRICS_ENDPOINT: "${METRICS_ENDPOINT}"
  METRICS_PORT: "${METRICS_PORT}"

  CLOUD_STORAGE_CONCURRENT: "${CLOUD_STORAGE_CONCURRENT}"
  CLOUD_STORAGE_SINGLE_FILE_SIZE: "${CLOUD_STORAGE_SINGLE_FILE_SIZE}"
  CLOUD_STORAGE_TOTAL_SIZE: "${CLOUD_STORAGE_TOTAL_SIZE}"
  CLOUD_STORAGE_PREFIX_PATH: "${CLOUD_STORAGE_PREFIX_PATH}"
  CLOUD_STORAGE_ALLOW_FILE_SUFFIX: "${CLOUD_STORAGE_ALLOW_FILE_SUFFIX}"
  CLOUD_STORAGE_ALLOW_URL_FILE_SUFFIX: "${CLOUD_STORAGE_ALLOW_URL_FILE_SUFFIX}"
  WEB_WECHAT_APP_ID: "${WEB_WECHAT_APP_ID}"
  WEB_WECHAT_APP_SECRET: "${WEB_WECHAT_APP_SECRET}"
  MOBILE_WECHAT_APP_ID: "${MOBILE_WECHAT_APP_ID}"
  MOBILE_WECHAT_APP_SECRET: "${MOBILE_WECHAT_APP_SECRET}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  GOOGLE_REDIRECT_URI: "${GOOGLE_REDIRECT_URI}"
  AGORA_APP_ID: "${AGORA_APP_ID}"
  AGORA_APP_CERTIFICATE: "${AGORA_APP_CERTIFICATE}"
  AGORA_RESTFUL_ID: "${AGORA_RESTFUL_ID}"
  AGORA_RESTFUL_SECRET: "${AGORA_RESTFUL_SECRET}"
  AGORA_OSS_VENDOR: "${AGORA_OSS_VENDOR}"
  AGORA_OSS_ACCESS_KEY_ID: "${AGORA_OSS_ACCESS_KEY_ID}"
  AGORA_OSS_ACCESS_KEY_SECRET: "${AGORA_OSS_ACCESS_KEY_SECRET}"
  AGORA_OSS_REGION: "${AGORA_OSS_REGION}"
  AGORA_OSS_BUCKET: "${AGORA_OSS_BUCKET}"
  AGORA_OSS_FOLDER: "${AGORA_OSS_FOLDER}"
  AGORA_OSS_PREFIX: "${AGORA_OSS_PREFIX}"
  NETLESS_ACCESS_KEY: "${NETLESS_ACCESS_KEY}"
  NETLESS_SECRET_ACCESS_KEY: "${NETLESS_SECRET_ACCESS_KEY}"
  ALIBABA_CLOUD_OSS_ACCESS_KEY: "${ALIBABA_CLOUD_OSS_ACCESS_KEY}"
  ALIBABA_CLOUD_OSS_ACCESS_KEY_SECRET: "${ALIBABA_CLOUD_OSS_ACCESS_KEY_SECRET}"
  ALIBABA_CLOUD_OSS_ENDPOINT: "${ALIBABA_CLOUD_OSS_ENDPOINT}"
  ALIBABA_CLOUD_HANGCHOW_OSS_BUCKET: "${ALIBABA_CLOUD_HANGCHOW_OSS_BUCKET}"
  ALIBABA_CLOUD_HANGCHOW_OSS_REGION: "${ALIBABA_CLOUD_HANGCHOW_OSS_REGION}"
  ALIBABA_CLOUD_SILICONVALLEY_OSS_BUCKET: "${ALIBABA_CLOUD_SILICONVALLEY_OSS_BUCKET}"
  ALIBABA_CLOUD_SILICONVALLEY_OSS_REGION: "${ALIBABA_CLOUD_SILICONVALLEY_OSS_REGION}"
  ALIBABA_CLOUD_SINGAPORE_OSS_BUCKET: "${ALIBABA_CLOUD_SINGAPORE_OSS_BUCKET}"
  ALIBABA_CLOUD_SINGAPORE_OSS_REGION: "${ALIBABA_CLOUD_SINGAPORE_OSS_REGION}"
  ALIBABA_CLOUD_MUMBAI_OSS_BUCKET: "${ALIBABA_CLOUD_MUMBAI_OSS_BUCKET}"
  ALIBABA_CLOUD_MUMBAI_OSS_REGION: "${ALIBABA_CLOUD_MUMBAI_OSS_REGION}"
  ALIBABA_CLOUD_LONDON_OSS_BUCKET: "${ALIBABA_CLOUD_LONDON_OSS_BUCKET}"
  ALIBABA_CLOUD_LONDON_OSS_REGION: "${ALIBABA_CLOUD_LONDON_OSS_REGION}"

